name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # hub コマンドをインストールする
      - name: install hub
        uses: geertvdc/setup-hub@v2.14.2

      # masterブランチをチェックアウトする
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      # プルリクを作成する
      - name: Create Pull Request
        env:
          TZ: 'Asia/Tokyo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d_%H:%M:%S"`
          PULL_REQUEST_NAME="release_$DATE"
          hub pull-request -m "$PULL_REQUEST_NAME" -b production -h master
